language: python
services:
  - memcached
  - redis-server
python:
  - "2.6"
  - "2.7"
install:
  - pip install -e .
  - pip install -r requirements.txt "$DJANGO_SPEC"
script:
  - fab test
env:
  - DJANGO_SPEC="Django>=1.4,<1.5"
  - DJANGO_SPEC="Django>=1.5,<1.6"
  - DJANGO_SPEC="Django>=1.6,<1.7"
  - DJANGO_SPEC="Django>=1.7,<1.8"
